# autogenerated file

OBJECTS += fcfutils.o fcfmain.o module_testLoggerScreen.o module_mouse_clark.o module_mouse_clark2.o module_profile.o utils_libusb-1.0.o

fcfmain.c fcfmain.h: Main.miml Control.miml IMU.miml Logger.miml SensorFusion.miml
	codeGen.py -c Main.miml		#generates fcfmain.c
	codeGen.py -h Main.miml		#generates fcfmain.h
	


